defaults: &defaults
  client:
    origin: http://localhost
  twitter:
    clientId: "qTXkEyqedrWBf4LvoYf2Q"
    clientSecret: "cwjwn2X8NcWtETuKjyoEX8S1QBBOoj25IAzFJ7NgAA"


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
    
